### ISSUE TITLE
wicked ifup all segfault

### ISSUE THREAD

**Issue by dgloe** [openSUSE/wicked#531]
wicked is segfaulting when running ifup all. This is causing systemd to think networking has failed. It started when I changed a dhcp interface to static by updating its ifcfg file and running systemctl restart network.

```
linux:~ # ifconfig
eth0      Link encap:Ethernet  HWaddr 14:FE:B5:CA:B7:00
          inet addr:10.142.0.8  Bcast:10.142.0.255  Mask:255.255.255.0
          inet6 addr: fe80::16fe:b5ff:feca:b700/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1213 errors:0 dropped:0 overruns:0 frame:0
          TX packets:772 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:106968 (104.4 Kb)  TX bytes:114266 (111.5 Kb)

eth1      Link encap:Ethernet  HWaddr 14:FE:B5:CA:B7:02
          inet addr:172.30.48.100  Bcast:172.30.63.255  Mask:255.255.240.0
          inet6 addr: fe80::16fe:b5ff:feca:b702/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:898316 errors:0 dropped:0 overruns:0 frame:0
          TX packets:28 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:153017101 (145.9 Mb)  TX bytes:1960 (1.9 Kb)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:74 errors:0 dropped:0 overruns:0 frame:0
          TX packets:74 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:5532 (5.4 Kb)  TX bytes:5532 (5.4 Kb)
linux:~ # wicked --version
wicked 0.6.12
linux:~ # /usr/sbin/wicked --log-level debug --systemd ifup all
lo              up
eth0            up
Segmentation fault

2015-04-01T21:37:20.564210+00:00 linux wicked[15560]: __ni_config_parse_ifconfig_source: Adding ifconfig firmware:
2015-04-01T21:37:20.564641+00:00 linux wicked[15560]: __ni_config_parse_ifconfig_source: Adding ifconfig compat:
2015-04-01T21:37:20.564869+00:00 linux wicked[15560]: __ni_config_parse_ifconfig_source: Adding ifconfig wicked:/etc/wicked/ifconfig
2015-04-01T21:37:20.576954+00:00 linux wicked[15560]: trying to discover netif config via firmware service "ibft"
2015-04-01T21:37:20.583308+00:00 linux wicked[15560]: ni_netconfig_firmware_discovery: buffer  has 0 bytes
2015-04-01T21:37:20.583593+00:00 linux wicked[15560]: ni_ifconfig_read_firmware: location: firmware:, line: 0
2015-04-01T21:37:20.583822+00:00 linux wicked[15560]: ni_sysconfig_read(/etc/sysconfig/network/config)
2015-04-01T21:37:20.584069+00:00 linux wicked[15560]: ni_sysconfig_read(/etc/sysconfig/network/dhcp)
2015-04-01T21:37:20.584286+00:00 linux wicked[15560]: Reading sysctl file '/etc/sysctl.conf'
2015-04-01T21:37:20.584499+00:00 linux wicked[15560]: ni_sysconfig_read(/etc/sysconfig/network/ifcfg-eth0)
2015-04-01T21:37:20.584707+00:00 linux wicked[15560]: ni_sysconfig_read(/etc/sysconfig/network/ifcfg-lo)
2015-04-01T21:37:20.584915+00:00 linux wicked[15560]: ni_sysconfig_read(/etc/sysconfig/network/ifcfg-eth1)
2015-04-01T21:37:20.585123+00:00 linux wicked[15560]: ni_compat_generate_interfaces: location: compat:/etc/sysconfig/network/ifcfg-eth0, line: 0
2015-04-01T21:37:20.585343+00:00 linux wicked[15560]: ni_compat_generate_interfaces: location: compat:/etc/sysconfig/network/ifcfg-lo, line: 0
2015-04-01T21:37:20.585557+00:00 linux wicked[15560]: ni_compat_generate_interfaces: location: compat:/etc/sysconfig/network/ifcfg-eth1, line: 0
2015-04-01T21:37:20.585769+00:00 linux wicked[15560]: No valid configuration files found at /etc/wicked/ifconfig
2015-04-01T21:37:20.585984+00:00 linux wicked[15560]: skipping eth2 interface: no configuration provided
2015-04-01T21:37:20.586199+00:00 linux wicked[15560]: skipping eth3 interface: no configuration provided
2015-04-01T21:37:20.586410+00:00 linux wicked[15560]: skipping ib0 interface: no configuration provided
2015-04-01T21:37:20.586622+00:00 linux wicked[15560]: skipping ib1 interface: no configuration provided
2015-04-01T21:37:20.604939+00:00 linux wickedd[902]: lo: address 127.0.0.1 covered by a static lease
2015-04-01T21:37:20.891354+00:00 linux wickedd[902]: lo: address ::1 covered by a static lease
2015-04-01T21:37:21.179200+00:00 linux wickedd[902]: eth0: address 10.142.0.8 covered by a static lease
2015-04-01T21:37:21.816267+00:00 linux wickedd[902]: eth0: No duplicates for IP address 10.142.0.8 detected
2015-04-01T21:37:21.856250+00:00 linux wickedd[902]: eth0: Notified neighbours about IP address 10.142.0.8
2015-04-01T21:37:22.143465+00:00 linux wickedd[902]: eth1: address 172.30.48.100 covered by a static lease
2015-04-01T21:37:22.776246+00:00 linux wickedd[902]: eth1: No duplicates for IP address 172.30.48.100 detected
2015-04-01T21:37:22.812245+00:00 linux wickedd[902]: eth1: Notified neighbours about IP address 172.30.48.100
2015-04-01T21:37:23.108071+00:00 linux kernel: [189066.669682] wicked[15560]: segfault at 24 ip 00000000004133dc sp 00007fff4cdbd8b0 error 4 in wicked[400000+29000]

Core was generated by `/usr/sbin/wicked --log-level debug --systemd ifup all'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __find_grouped_lease (dev=dev@entry=0x1e4f910, lease=lease@entry=0x1e7b220) at ifstatus.c:124
124	ifstatus.c: No such file or directory.
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.19-18.1.x86_64 libdbus-1-3-debuginfo-1.8.8-1.12.x86_64 libgcrypt20-debuginfo-1.6.1-9.1.x86_64 libgpg-error0-debuginfo-1.13-1.79.x86_64 libnl3-200-debuginfo-3.2.23-2.21.x86_64 libwicked-0-6-debuginfo-0.6.12-4.1.x86_64
(gdb) bt full
#0  __find_grouped_lease (dev=dev@entry=0x1e4f910, lease=lease@entry=0x1e7b220) at ifstatus.c:124
        other = 0x0
#1  0x000000000041372f in __find_grouped_lease_state (lease=0x1e7b220, dev=0x1e4f910) at ifstatus.c:148
        other = <optimized out>
#2  __ifstatus_of_device_lease (st=<synthetic pointer>, lease=0x1e7b220, dev=0x1e4f910) at ifstatus.c:165
No locals.
#3  __ifstatus_of_device_leases (st=<synthetic pointer>, dev=0x1e4f910) at ifstatus.c:233
        lease = 0x1e7b220
#4  __ifstatus_of_device (dev=0x1e4f910) at ifstatus.c:286
        st = 0
#5  ni_ifstatus_of_device (dev=0x1e4f910, mandatory=<optimized out>) at ifstatus.c:308
        mandatory = <optimized out>
        dev = 0x1e4f910
#6  0x00000000004149e1 in ni_ifstatus_of_worker (mandatory=0x7fff4cdbd97f "", w=0x1e57330) at ifstatus.c:317
        dev = <optimized out>
        st = <optimized out>
#7  ni_ifstatus_display_result (fsm=fsm@entry=0x1df1a70, names=names@entry=0x7fff4cdbda40, marked=marked@entry=0x7fff4cdbda20,
    opt_transient=opt_transient@entry=0 '\000') at ifstatus.c:920
        w = 0x1e57330
        st = 157
        mandatory = 0 '\000'
        stcodes = {count = 2, data = 0x1e7aa80}
        stflags = {count = 2, data = 0x1e7aad0}
        status = 0
        multiple = 1 '\001'
        i = 2
#8  0x0000000000410e91 in ni_do_ifup_direct (argv=0x7fff4cdbdc98, argc=2) at ifup.c:904
        timeout = 0
        ifmarked = {count = 3, data = 0x1e034e0}
        opt_transient = 0 '\000'
        nmarked = <optimized out>
        ptr = <optimized out>
        ifnames = {count = 0, data = 0x0}
        c = <optimized out>
        status = 2
        ifmatch = {name = 0x0, mode = 0x0, boot_stage = 0x0, skip_origin = 0x0, require_config = 1, require_configured = 0,
          allow_persistent = 1, ignore_startmode = 0, skip_active = 0, ifdown = 0}
        ifmarker = {target_range = {min = 10, max = 11}, persistent = 0}
---Type <return> to continue, or q <return> to quit---
        opt_ifconfig = {count = 3, data = 0x1e68380}
        check_prio = 1 '\001'
        fsm = 0x1df1a70
        ifup_options = {{name = 0x42020a "help", has_arg = 0, flag = 0x0, val = 0}, {name = 0x420b0f "ifconfig", has_arg = 1,
            flag = 0x0, val = 1}, {name = 0x4203fd "mode", has_arg = 1, flag = 0x0, val = 2}, {name = 0x420402 "boot-stage",
            has_arg = 1, flag = 0x0, val = 3}, {name = 0x420b47 "skip-active", has_arg = 1, flag = 0x0, val = 5}, {
            name = 0x420b53 "skip-origin", has_arg = 1, flag = 0x0, val = 6}, {name = 0x420766 "timeout", has_arg = 1,
            flag = 0x0, val = 4}, {name = 0x420b5f "transient", has_arg = 0, flag = 0x0, val = 8}, {
            name = 0x42040d "persistent", has_arg = 0, flag = 0x0, val = 7}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
#9  ni_do_ifup (argc=2, argv=0x7fff4cdbdc98) at ifup.c:928
No locals.
#10 0x000000000040b7d3 in main (argc=6, argv=0x7fff4cdbdc78) at main.c:268
        cmd = 0x7fff4cdbe0ff "ifup"
        c = <optimized out>
        status = 2
```

**Comment by mtomaschewski** [comment]
fixed in commit bcdfdeb8 & released in 0.6.14 (bsc#908554)
